# Generated by Django 5.1.1 on 2024-10-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aot1', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_age', models.IntegerField()),
                ('emp_phno', models.CharField(max_length=11)),
            ],
        ),
    ]
