# Generated by Django 5.1.1 on 2024-10-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aot1', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_desc', models.TextField()),
                ('pro_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_qnty', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
