# Generated by Django 5.1.1 on 2024-10-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aot1', '0004_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_qnty',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_qntuy',
            field=models.IntegerField(null=True),
        ),
    ]
