# Generated by Django 5.1.1 on 2024-10-16 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aot1', '0008_alter_blog_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='productmodel',
            fields=[
                ('pro_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=100)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aot1.user')),
            ],
        ),
    ]
