# Generated by Django 5.1.1 on 2024-11-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aot1', '0016_userreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('user_img', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
