# Generated by Django 5.1.1 on 2024-11-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aot1', '0017_userimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='image/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
