# Generated by Django 5.1.1 on 2024-11-04 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aot1', '0018_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Image',
            new_name='Image_up',
        ),
    ]
