# Generated by Django 5.1.1 on 2024-11-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aot1', '0019_rename_image_image_image_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='userrrrmodel',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
